/* This file was generated by syncqt. */
#ifndef QT_QTOPCUA_VERSION_H
#define QT_QTOPCUA_VERSION_H

#define QTOPCUA_VERSION_STR "5.15.0"

#define QTOPCUA_VERSION 0x050F00

#endif // QT_QTOPCUA_VERSION_H
